In [1]:
# Computation libraries
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Inputs to the neural network
inputs = np.array([
    [1, 2, 3, 2.5],
    [2., 5., -1., 2],
    [-1.5, 2.7, 3.3, -0.8]
])

# Set of weights
layer_1_weights = np.array([
    [0.2, 0.8, -0.5, 1],
    [0.5, -0.91, 0.26, -0.5],
    [-0.26, -0.27, 0.17, 0.87]
])

layer_2_weights = np.array([
    [0.1, -0.14, 0.5],
    [-0.5, 0.12, -0.33],
    [-0.44, 0.73, -0.13]
])

# Biases
layer_1_bias = np.array([2, 3, 0.5])
layer_2_bias = np.array([-1, 2, -0.5])

In [3]:
# Run dot product for each layer
layer_1_output = np.dot(inputs, layer_1_weights.T) + layer_1_bias
layer_2_output = np.dot(layer_1_output, layer_2_weights.T) + layer_2_bias

# Show layer 2 output
print(layer_2_output)

[[ 0.50310004 -1.04184985 -2.03874993]
 [ 0.24339998 -2.73320007 -5.76329994]
 [-0.99314     1.41254002 -0.35655001]]
